---
- name: Write config template for ssh_config.
  template:
    src: ssh_config.j2
    dest: "{{ ssh_config_path }}/{{ ssh_config_file }}"
    owner: "{{ ssh_config_user }}"
    group: "{{ ssh_config_group }}"
    mode: 0644

- name: Remove old config.d directory
  file:
    path: "{{ ssh_config_path }}/config.d"
    state: absent
