---
# tasks file for ajsalminen.ssh_config

- name: Ensure config.d exists
  file:
    path: "{{ ssh_config_fragment_path }}"
    state: directory
    owner: root
    group: root
    mode: 0700


- name: Write base config template for ssh_config.
  template:
    src: ssh_config_base.j2
    dest: "{{ ssh_config_fragment_path }}/00_base"

- name: Assemble ssh_config from fragments.
  assemble:
    src: "{{ ssh_config_fragment_path }}"
    dest: "{{ ssh_config_path }}/ssh_config"
    owner: root
    group: root
    mode: 0644