---
# handlers file for ajsalminen.ssh_config
- name: Assemble ssh_config from fragments.
  assemble:
    src: "{{ ssh_config_fragment_path }}"
    dest: "{{ ssh_config_path }}/ssh_config"
    owner: root
    group: root
    mode: 0644
